# Generated by Django 4.0.1 on 2022-06-15 15:07

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Admin',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Email', models.CharField(max_length=50)),
                ('Senha', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='Agricultor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Nome', models.CharField(max_length=100)),
                ('CPF', models.IntegerField(max_length=11)),
                ('Telefone', models.IntegerField(max_length=11)),
            ],
        ),
        migrations.CreateModel(
            name='Colheita',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Tipo', models.CharField(max_length=50)),
                ('Quantidade', models.DecimalField(decimal_places=2, max_digits=15)),
                ('AnoDaColheita', models.IntegerField(max_length=10)),
            ],
        ),
        migrations.CreateModel(
            name='Endereco',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('CEP', models.IntegerField(max_length=8)),
                ('Cidade', models.CharField(max_length=50)),
                ('Bairro', models.CharField(max_length=50)),
                ('Rua', models.CharField(max_length=50)),
                ('Numero', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='Motorista',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Nome', models.CharField(max_length=100)),
                ('Matricula', models.IntegerField(max_length=11)),
                ('CNH', models.IntegerField(max_length=11)),
                ('Categoria', models.CharField(max_length=1)),
            ],
        ),
        migrations.CreateModel(
            name='Propriedade',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Nome', models.CharField(max_length=100)),
                ('Proprietario', models.IntegerField(max_length=11)),
                ('Area', models.IntegerField(max_length=20)),
            ],
        ),
        migrations.CreateModel(
            name='Veiculo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Modelo', models.CharField(max_length=50)),
                ('Marca', models.CharField(max_length=50)),
                ('AnoDeFabricacao', models.IntegerField(max_length=10)),
            ],
        ),
    ]
